version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: airflow_postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks: [airnet]

  airflow-scheduler:
    image: apache/airflow:2.9.1
    container_name: airflow_scheduler
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "False"
      AIRFLOW__WEBSERVER__SECRET_KEY: "mysecret"
      # провайдер для DockerOperator
      PIP_ADDITIONAL_REQUIREMENTS: "apache-airflow-providers-docker==3.12.0 docker==6.1.3"
    volumes:
      - ./dags:/opt/airflow/dags
      - shared_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    command: >
      bash -lc "
        airflow db upgrade &&
        airflow users create
          --username admin
          --password admin
          --firstname Admin
          --lastname User
          --role Admin
          --email admin@example.com || true &&
        airflow scheduler
      "
    restart: always
    networks: [airnet]

  airflow-webserver:
    image: apache/airflow:2.9.1
    container_name: airflow_webserver
    depends_on:
      - postgres
      - airflow-scheduler
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__WEBSERVER__SECRET_KEY: "mysecret"
      PIP_ADDITIONAL_REQUIREMENTS: "apache-airflow-providers-docker==3.12.0 docker==6.1.3"
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - shared_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    command: webserver
    restart: always
    networks: [airnet]

  spark-job-build:
    build:
      context: ./spark-job
      dockerfile: Dockerfile
    image: spark-compact-job:latest
    container_name: spark_job_build
    command: ["/bin/bash", "-c", "echo 'Spark job image built successfully'"]
    volumes:
      - shared_data:/data
    restart: "no"
    networks: [airnet]

volumes:
  postgres_data:
  shared_data:

networks:
  airnet:
    driver: bridge
